newContentEditor = "vim"
baseURL = "https://lunarxlark.github.io/"
defaultContentLanguage = "ja"
title = "/home/lunarxlark/.config/blog"
themes = "archie"
copyright = "© lunarxlark"
googleAnalytics = "G-HC9218ZECN"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=5

[params]
	mode="dark"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/lunarxlark/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/lunarxlark/"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://instagram.com/lunarxlark/"

# Main menu Items
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Articles"
url = "/articles"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
